"""rename department

Revision ID: 2a3cc1ac2f36
Revises: 2ef41927961c
Create Date: 2025-07-31 14:20:44.415745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a3cc1ac2f36'
down_revision = '2ef41927961c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
