"""rename address

Revision ID: 801180152c4b
Revises: 2a3cc1ac2f36
Create Date: 2025-07-31 14:24:15.666672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801180152c4b'
down_revision = '2a3cc1ac2f36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###